# Generated by Django 5.1.5 on 2025-02-12 02:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_signup_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannerdetail',
            name='wdate',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
